#' Release-candidate API catalog
#' @export
smf_api_catalog <- function() {
  p <- system.file("metadata","API_FREEZE_1.0.0.csv",package="sciModelFlowR")
  if(!nzchar(p)) p <- file.path("inst","metadata","API_FREEZE_1.0.0.csv")
  utils::read.csv(p,stringsAsFactors=FALSE,check.names=FALSE)
}

#' Optional-backend certification matrix
#' @export
smf_backend_matrix <- function() {
  p <- system.file("metadata","BACKEND_MATRIX_1.0.0.csv",package="sciModelFlowR")
  if(!nzchar(p)) p <- file.path("inst","metadata","BACKEND_MATRIX_1.0.0.csv")
  utils::read.csv(p,stringsAsFactors=FALSE,check.names=FALSE)
}

#' Return the 1.x deprecation policy contract
#' @export
smf_deprecation_policy <- function() list(
  api_freeze="1.0.0",
  stable_release="1.0.0",
  policy="No public symbol stable at 1.0.0 is removed or changes scientific meaning in 1.x without an explicit lifecycle, migration path, and validation evidence.",
  source="DEPRECATION_POLICY.md")

#' Validate neutral R/Python fixtures structurally
#' @export
smf_validate_crosslang_fixtures <- function(path=NULL) {
  if(is.null(path)) {
    path <- system.file("crosslang",package="sciModelFlowR")
    if(!nzchar(path)) path <- file.path("inst","crosslang")
  }
  files <- list.files(path,recursive=TRUE,full.names=TRUE)
  files <- files[file.info(files)$isdir %in% FALSE]
  rows <- lapply(files,function(f) {
    ext <- tolower(tools::file_ext(f)); ok <- TRUE; msg <- "ok"
    tryCatch({
      if(ext=="json") jsonlite::fromJSON(f,simplifyVector=FALSE)
      else if(ext=="csv") utils::read.csv(f,stringsAsFactors=FALSE,check.names=FALSE)
      else readLines(f,warn=FALSE)
    },error=function(e){ok<<-FALSE;msg<<-conditionMessage(e)})
    data.frame(file=sub(paste0("^",normalizePath(path,winslash="/"),"/?"),"",normalizePath(f,winslash="/")),passed=ok,message=msg,row.names=NULL)
  })
  if(length(rows)) do.call(rbind,rows) else data.frame(file=character(),passed=logical(),message=character())
}

#' Run cross-language fixture validation
#' @export
smf_run_crosslang_validation <- function(path=NULL) {
  structure(list(fixtures=smf_validate_crosslang_fixtures(path), contract="scientific quantities and neutral portable schemas; not identical RNG streams"), class="smf_crosslang_validation")
}

#' Run independent deterministic reference validation
#'
#' Reference scope (derived fix 1.0.0+; see DERIVED_PATCH_NOTES.md): the frozen
#' fixture `gold_linear_reference.json` was generated by OLS on the holdout
#' train rows with metrics evaluated on the held-out test rows
#' (`inst/crosslang/splits/gold_linear_holdout_v1.json`). Fitting on the full
#' dataset would leak test rows into estimation, so this gate fits on train
#' and evaluates on test, mirroring the fixture exactly.
#' @export
smf_run_reference_validation <- function(tolerance=list(prediction=1e-10, metric=1e-12)) {
  d <- smf_load_dataset("gold_linear_regression")
  sp_path <- system.file("crosslang","splits","gold_linear_holdout_v1.json",package="sciModelFlowR")
  if(!nzchar(sp_path)) sp_path <- file.path("inst","crosslang","splits","gold_linear_holdout_v1.json")
  sp <- jsonlite::fromJSON(sp_path,simplifyVector=TRUE)
  train_ids <- unlist(sp$train_ids); test_ids <- unlist(sp$test_ids)
  tr <- d[d$obs_id %in% train_ids,]; te <- d[d$obs_id %in% test_ids,]
  fit <- stats::lm(yield ~ nitrogen + rainfall + soil_n, data=tr)
  co <- stats::coef(fit); pred <- as.numeric(stats::predict(fit,te))
  ref_path <- system.file("crosslang","expected","gold_linear_reference.json",package="sciModelFlowR")
  if(!nzchar(ref_path)) ref_path <- file.path("inst","crosslang","expected","gold_linear_reference.json")
  ref <- jsonlite::fromJSON(ref_path,simplifyVector=TRUE)
  expected <- c(`(Intercept)`=ref$coefficients$intercept,nitrogen=ref$coefficients$nitrogen,rainfall=ref$coefficients$rainfall,soil_n=ref$coefficients$soil_n)
  rmse <- sqrt(mean((te$yield-pred)^2)); mae <- mean(abs(te$yield-pred))
  coef_err <- max(abs(co[names(expected)]-expected))
  metric_err <- max(abs(c(rmse-ref$rmse,mae-ref$mae)))
  list(passed=isTRUE(coef_err <= tolerance$prediction && metric_err <= max(tolerance$metric,1e-8)),
       coefficients=co, expected_coefficients=expected, coefficient_max_abs_error=coef_err,
       metrics=data.frame(metric=c("rmse","mae"),observed=c(rmse,mae),expected=c(ref$rmse,ref$mae)),
       metric_max_abs_error=metric_err, reference=ref$reference)
}

#' Audit stable-release source evidence without claiming unexecuted runtime certification
#' @export
smf_release_candidate_audit <- function(runtime_certified=FALSE) {
  api <- smf_api_catalog(); gold <- smf_run_gold_validation(FALSE); cross <- smf_validate_crosslang_fixtures()
  backend <- smf_backend_matrix(); blockers <- character()
  if(any(!gold$passed)) blockers <- c(blockers,"Gold hash mismatch")
  if(any(!cross$passed)) blockers <- c(blockers,"Cross-language fixture parse failure")
  if(nrow(api)!=246L) blockers <- c(blockers,"API-freeze export count differs from 246")
  if(!isTRUE(runtime_certified)) blockers <- c(blockers,"Runtime/numerical certification intentionally deferred")
  p <- system.file("metadata","API_FREEZE_1.0.0.sha256",package="sciModelFlowR")
  if(!nzchar(p)) p <- file.path("inst","metadata","API_FREEZE_1.0.0.sha256")
  api_hash <- if(file.exists(p)) strsplit(readLines(p,warn=FALSE)[1],"\\s+")[[1]][1] else digest::digest(api,algo="sha256")
  ReleaseCandidateAudit(api_hash=api_hash,n_exports=as.integer(nrow(api)),backend_matrix=backend,
    gold=gold,crosslang=cross,blockers=blockers,runtime_certified=isTRUE(runtime_certified),
    status=if(length(blockers)==1L && grepl("intentionally deferred",blockers)) "source-complete-validation-deferred" else if(!length(blockers)) "certification-ready" else "blocked")
}
